import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
mkdirSync('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173',{waitUntil:'domcontentloaded'});
await page.getByRole('button',{name:'展开道具',exact:true}).click();
await page.getByRole('button',{name:/遥控骰子/}).click();
await page.getByRole('button',{name:'选择 1 点',exact:true}).click();
await page.getByRole('button',{name:/掷骰子/}).click();
await page.getByRole('button',{name:'购买 ¥ 2,200'}).click();
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('city-dice-v1')).properties[1].owner),0);
await page.getByRole('button',{name:'结束回合'}).click();
const deadline=Date.now()+60000;
while(true){
 const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('city-dice-v1')));
 if(s.round===2&&s.current===0)break;
 assert.ok(Date.now()<deadline,'AI round finishes after owner decisions');
 if(s.phase==='offer'&&s.offer.seller===0)await page.getByRole('button',{name:'拒绝收购',exact:true}).click();
 await page.waitForTimeout(200);
}
const before=await page.evaluate(()=>localStorage.getItem('city-dice-v1'));
await page.reload({waitUntil:'domcontentloaded'});
assert.equal(await page.evaluate(()=>localStorage.getItem('city-dice-v1')),before);
await page.getByRole('button',{name:'城市图鉴',exact:true}).click();
await page.getByRole('group',{name:'城市范围'}).getByRole('button',{name:/当前棋盘/}).click();
assert.equal(await page.locator('.city-collection>button').count(),12);
await page.getByRole('button',{name:/北京/}).click();
await page.getByRole('button',{name:'关闭',exact:true}).click();
await page.getByRole('button',{name:'游戏规则',exact:true}).click();
await page.getByRole('button',{name:'关闭',exact:true}).last().click();
await page.getByRole('button',{name:'城市棋盘',exact:true}).click();
await page.screenshot({path:'artifacts/desktop-played.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile must not overflow');
await page.getByRole('button',{name:'展开道具',exact:true}).click();
await page.getByRole('button',{name:/租金护盾/}).click();
await page.getByRole('dialog').getByRole('button',{name:'使用',exact:true}).click();
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('city-dice-v1')).players[0].shield),true);
await page.getByRole('button',{name:'重新开始',exact:true}).click();
await page.getByRole('button',{name:'确认重开',exact:true}).click();
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('city-dice-v1')).round),1);
assert.equal(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('city-dice-v1')).properties).length),0);
await page.screenshot({path:'artifacts/mobile-fresh.png',fullPage:true});
assert.deepEqual(errors,[]);
console.log('PASS: controlled dice, purchase, 3 AI turns, reload persistence, 12-city album, details, rules, mobile layout, shield, restart; no JS errors.');
await browser.close();
