import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Map,BookOpen,Volume2,VolumeX,RotateCcw,ChevronRight,ArrowUpRight,ArrowRight,ArrowDown,Flag,TrainFront,Sparkles,Gift,Palmtree,Store,Flower2,Coins,Building2,Shield,Dices,Hammer,X,Check,Compass,HelpCircle,Backpack,Trophy,ChevronDown} from 'lucide-react';
import {CARDS,season,owned,ownedIndustries,holdings,propertyEquity,ownerName,ownerColor,worth,money,initialState,transition,rent,upgradeCost,getIndustryQuote,aiAction,roundLimit} from './game.js';
import {EventLabPicker,EventLabBar} from './EventLab.jsx';
import {createEventTestState,prepareItemTrial} from './eventLab.js';
import {loadGame,loadNormalGame,saveGame} from './gameStorage.js';
import {EventCards} from './EventCards.jsx';
import {CityEvents} from './CityEvents.jsx';
import {eligibleCityEventCards} from './eventCards.js';
import {PropertyActions} from './PropertyActions.jsx';
import {IndustryDetails} from './IndustryDetails.jsx';
import {PropertyPortfolio} from './PropertyPortfolio.jsx';
import {BoardHub} from './BoardHub.jsx';
import {useBoardViewport} from './useBoardViewport.js';
import {BoardViewportControls} from './BoardViewportControls.jsx';
import {MapEditor} from './MapEditor.jsx';
import {getTiles,getGroups,validateMap,MAP_SCOPES} from './board.js';
import {useGameController} from './useGameController.js';
import {AnimatedMoney,MoneyEffects} from './Effects.jsx';
import {FxLayer,Podium,DiceRoll} from './FxLayer.jsx';
import {createGameAudio} from './audio.js';
import {CityLibrary, CatalogCityDetails} from './CityLibrary.jsx';
import {PixelPlayer} from './PixelPlayer.jsx';
import {AppearanceEditor} from './AppearanceEditor.jsx';
import {MAX_PLAYERS,nextPlayerName,validRosterSave} from './players.js';
import {migrateAppearances,randomAppearance} from './appearance.js';
import './style.css';
import './depth.css';
import './compact.css';
import './city-library.css';
import './appearance.css';
import './players.css';
import './map.css';
import './board-hub.css';
import './property-actions.css';
import './event-cards.css';
import './board-viewport.css';
import './readability.css';
import './fx.css';
function neutralText(text=''){return text.replace('旅程开始！每位旅行者获得 ¥12,000。','对局开始，每位玩家初始现金 ¥12,000。').replace('，旅途中有了新的家。','。').replace(' 总资产赢得本次旅行！',' 总资产获胜。').replace('享受度假时光，获得','获得度假奖励').replace('你的旅程，从这里开始。','等待掷骰。').replaceAll('购入','购买');}
function load(){try{return loadGame(localStorage);}catch{return initialState();}}
function originalSave(){try{return loadNormalGame(localStorage);}catch{return initialState();}}
const SPECIAL={start:Flag,'city-event':Building2,chance:Sparkles};
const CARDICON={dice:Dices,shield:Shield,build:Hammer};
function Die({value=1,small=false}){const dots={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]}[value];return <span className={`die ${small?'small':''}`}>{Array.from({length:9},(_,i)=><i key={i} className={dots.includes(i)?'dot':''}/>)}</span>;}

function App(){
 const [tab,setTab]=useState('game'),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[sound,setSound]=useState(()=>{try{return localStorage.getItem('city-dice-sound')!=='off';}catch{return true;}}),[saved,setSaved]=useState(true),[wallet,setWallet]=useState(0),[playersOpen,setPlayersOpen]=useState(false),[participants,setParticipants]=useState([]),[catalogCity,setCatalogCity]=useState(null),[newCharacter,setNewCharacter]=useState(null);
 const audio=useRef(null),originalGame=useRef(null);
 useEffect(()=>{const engine=createGameAudio();audio.current=engine;engine.enable(sound);const unlock=()=>engine.unlock();const hidden=()=>{if(document.hidden)engine.stop();};window.addEventListener('pointerdown',unlock,{capture:true});window.addEventListener('keydown',unlock,{capture:true});document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('pointerdown',unlock,{capture:true});window.removeEventListener('keydown',unlock,{capture:true});document.removeEventListener('visibilitychange',hidden);engine.dispose();audio.current=null;};},[]);
 useEffect(()=>{audio.current?.enable(sound);try{localStorage.setItem('city-dice-sound',sound?'on':'off');}catch{}},[sound]);
 const {game,motion,mapMotion,animating,shownDice:displayDice,finance,dispatch,reset,replaceGame,updateAppearance,addCharacter,commit,renameCharacter,setRoundLimit}=useGameController(load,playSound,modal==='event-lab');
 const TILES=getTiles(game),GROUPS=getGroups(game),viewport=useBoardViewport(TILES.length,tab==='game'),{dimensions,position}=viewport,mapName=MAP_SCOPES[game.map?.kind||'classic'],cityEventCount=eligibleCityEventCards(game).length;
 const current=game.players[game.current],human=game.players[0],rolling=motion?.phase==='dice',busy=game.current!==0||animating,climate=season(game);
 const shownPosition=id=>motion?.player===id?motion.at:game.players[id].pos;
 useEffect(()=>{const strip=document.querySelector('.roster-strip'),person=strip?.querySelector('.current');if(!person)return;const a=strip.getBoundingClientRect(),b=person.getBoundingClientRect();if(b.left<a.left)strip.scrollLeft+=b.left-a.left;else if(b.right>a.right)strip.scrollLeft+=b.right-a.right;},[game.current,game.round]);
 useEffect(()=>{try{saveGame(localStorage,game);setSaved(true);}catch{setSaved(false);}},[game]);
 useEffect(()=>{if(viewport.desktop||motion?.phase!=='dice')return;const board=document.querySelector('.board');if(!board)return;const r=board.getBoundingClientRect();if(r.top<100||r.bottom>innerHeight-100)window.scrollTo({top:Math.max(0,scrollY+r.top-110),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[motion?.phase,viewport.desktop]);
 useEffect(()=>{if(!viewport.desktop&&mapMotion?.phase==='out'&&!modal&&tab==='game')document.querySelector('.board-scroll')?.scrollIntoView({block:'center',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[mapMotion?.phase,modal,tab,viewport.desktop]);
 useEffect(()=>{setSelected(null);setModal(value=>value==='tile'?null:value);},[game.map?.cityOrder?.join(',')]);
 useEffect(()=>{if(!viewport.desktop&&!animating&&!modal&&tab==='game'&&['draw','event','event-destination','event-choice'].includes(game.phase))document.getElementById('event-panel')?.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[game.phase,animating,modal,tab,viewport.desktop]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement;const dialog=document.querySelector('[role=dialog]');const focusables=()=>[...dialog.querySelectorAll('button:not(:disabled), input:not(:disabled), select:not(:disabled), a[href], [tabindex="0"]')];focusables()[0]?.focus();const handler=e=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const items=focusables(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=overflow;previous?.focus();};},[modal]);

 useEffect(()=>{
  if(!motion||modal||tab!=='game')return;
  const tile=document.querySelector(`[data-tile="${motion.at}"]`),behavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth';
  if(viewport.desktop){
   if(viewport.zoom===1||!tile)return;
   const frame=viewport.viewportRef.current,a=frame.getBoundingClientRect(),b=tile.getBoundingClientRect();
   const left=b.left<a.left+8?b.left-a.left-8:b.right>a.right-8?b.right-a.right+8:0;
   const top=b.top<a.top+8?b.top-a.top-8:b.bottom>a.bottom-8?b.bottom-a.bottom+8:0;
   if(left||top)frame.scrollBy({left,top,behavior});
  }else tile?.scrollIntoView({block:'nearest',inline:'nearest',behavior});
 },[motion?.at,modal,tab,viewport.desktop,viewport.zoom]);
 function playSound(type,detail){audio.current?.play(type,detail);}
 function toggleSound(){const next=!sound;audio.current?.enable(next);if(next)audio.current?.unlock();setSound(next);}
 function roll(){if(busy||game.phase!=='roll')return;dispatch({type:'ROLL',value:Math.floor(Math.random()*6)+1,eventSeed:Math.random()});}
 function startEventTest(id,variant='normal'){
  if(!game.testRun){originalGame.current=structuredClone(game);try{saveGame(localStorage,game);}catch{setSaved(false);}}
  const source=originalGame.current||originalSave();replaceGame(createEventTestState(source,id,variant));setModal(null);setTab('game');setSelected(null);
 }
 function exitEventTest(){const source=originalGame.current||originalSave();originalGame.current=null;replaceGame(source);setModal(null);setTab('game');setSelected(null);}
 function finishTurn(){if(game.testRun){if(game.phase==='end')setModal('event-lab');else replaceGame({...game,phase:'end',transactions:[]});}else dispatch({type:'END'});}
 function openWallet(id){setWallet(id);setModal('wallet');}
 function openToken(id){const ids=game.players.map((p,i)=>!p.bankrupt&&shownPosition(i)===shownPosition(id)?i:-1).filter(i=>i>=0);if(ids.length>1){setParticipants(ids);setModal('participants');}else openWallet(id);}
 function useCard(card,value){dispatch({type:'CARD',card,value});setModal(null);}
 const special=(t,size=28)=>{const Icon=SPECIAL[t.type];return Icon?<Icon size={size} strokeWidth={1.7}/>:null;};
 const decision=['draw','event','event-destination','event-choice'].includes(game.phase)?<div id="event-panel"><EventCards game={game} animating={animating} dispatch={dispatch}/></div>:['rent','offer','debt'].includes(game.phase)?<PropertyActions game={game} animating={animating} dispatch={dispatch}/>:null;
 return <div className={`app-shell ${tab==='game'?'game-view':''}`}>
 <header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('game');}}><span className="brand-icon"><DiceLogo/></span><span className="brand-name">monopoly</span></a><nav aria-label="主导航"><button className={tab==='game'?'nav-active':''} onClick={()=>setTab('game')}><Map size={17}/>城市棋盘</button><button className={tab==='album'?'nav-active':''} onClick={()=>setTab('album')}><BookOpen size={17}/>城市图鉴</button><button onClick={()=>setModal('rules')}><Compass size={17}/>游戏规则</button></nav><div className="header-actions"><span className="local-badge"><i/>本地单人 · {game.players.length-1} 位 AI</span><button className="icon-button" title={sound?'关闭音效':'开启音效'} aria-pressed={sound} aria-label={sound?'关闭音效':'开启音效'} onClick={toggleSound}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button className="icon-button" aria-label="重新开始" onClick={()=>game.testRun?startEventTest(game.testRun.id,game.testRun.variant):setModal('restart')}><RotateCcw size={17}/></button></div></header>
 <main><div className="page-heading"><div><h1>{game.testRun?'事件卡测试':'当前对局'}</h1></div><div className="trip-progress"><span><span className="live-dot"/>{game.phase==='finished'?'已结束':'进行中'}</span><b>第 <strong>{String(game.round).padStart(2,'0')}</strong> / {Number.isFinite(roundLimit(game))?roundLimit(game):'∞'} 轮</b></div></div>
 <div className="game-layout"><aside className="sidebar"><section className="travelers panel"><div className="roster-bar"><button className="fold-toggle" aria-expanded={playersOpen} aria-controls="player-details" aria-label={playersOpen?'收起玩家资产':'展开玩家资产'} onClick={()=>setPlayersOpen(!playersOpen)}>玩家<ChevronDown size={15}/></button><div className="roster-strip">{game.players.map((p,i)=><button key={i} className={`roster-person ${game.current===i?'current':''}`} aria-label={`查看${p.name}的资产`} onClick={()=>openWallet(i)} style={{'--player-color':p.color}}><PixelPlayer player={game.players[i]} id={i}/><span>{p.name}</span></button>)}</div><button className="roster-edit" aria-label="编辑我的昵称与外观" onClick={()=>{setWallet(0);setModal('appearance');}}>外观</button><button className="roster-add" aria-label="新增角色" disabled={!!game.testRun||game.players.length>=MAX_PLAYERS||game.phase==='finished'} onClick={()=>{setNewCharacter({name:nextPlayerName(game.players),appearance:randomAppearance()});setModal('add-player');}}>＋<span>新增</span><small>{game.players.length}/{MAX_PLAYERS}</small></button></div><div id="player-details" className="player-details" hidden={!playersOpen}>{game.players.map((p,i)=>{const change=finance?.to===i?finance.amount:finance?.from===i?-finance.amount:0;return <div key={i} data-player={i} className={`player-card ${game.current===i?'active':''} ${p.bankrupt?'bankrupt':''} ${change>0?'cash-gain':change<0?'cash-loss':''}`} style={{'--player-color':p.color}}><button className="player-main player-open" aria-label={`查看${p.name}的资产`} onClick={()=>openWallet(i)}><div className="avatar"><PixelPlayer player={game.players[i]} id={i}/></div><div className="player-identity"><h3>{p.name}</h3></div>{game.current===i&&<span className="turn-dot"/>}</button><div className="player-money" data-wallet={i}><span className="cash-label">可用现金</span><b><AnimatedMoney value={p.cash}/></b>{!!change&&<span key={finance.key} className={`cash-delta ${change>0?'positive':'negative'}`}>{change>0?'+':'−'}{money(Math.abs(change))}</span>}</div><div className="asset-breakdown"><span>产权净值 <b>{money(propertyEquity(game,i))}</b></span><span>总资产 <strong><AnimatedMoney value={worth(game,i)}/></strong></span></div><button className="wallet-button" onClick={()=>openWallet(i)}><Building2 size={12}/>{holdings(game,i).filter(k=>TILES[k].type==='city').length} 座城市 · {holdings(game,i).filter(k=>TILES[k].type==='industry').length} 项产业<span>资产明细 <ChevronRight size={11}/></span></button></div>})}</div></section></aside>

 <div className="play-area">{tab==='game'?<section className="board-panel"><div className="board-topline"><div><span className="map-mark"><Map size={18}/></span><b>{mapName}</b><span className="map-label">{TILES.length} 格{!viewport.desktop&&TILES.length>20?' · 滑动浏览':''}</span></div><div className="board-tools"><BoardViewportControls viewport={viewport}/><button className="city-events-entry" aria-label="查看本局城市事件" onClick={()=>setModal('city-events')}><Building2 size={12}/>城市事件 <span>· {cityEventCount}</span></button><button className="event-lab-entry" onClick={()=>setModal('event-lab')}><Sparkles size={13}/>事件卡测试</button><button className="map-settings" disabled={!!game.testRun} onClick={()=>setModal('map')}>地图设置</button></div></div>
 {game.testRun&&<EventLabBar game={game} animating={animating} onPick={()=>setModal('event-lab')} onRetry={()=>startEventTest(game.testRun.id,game.testRun.variant)} onExit={exitEventTest} onUseItem={()=>replaceGame(prepareItemTrial(game))}/>}
 <div className="board-scroll" ref={viewport.viewportRef} data-board-mode={viewport.desktop?(viewport.zoom===1?'fit':'zoom'):'scroll'}><div className="board-surface" style={viewport.surfaceStyle}><div className={`board ${viewport.desktop&&decision?'has-decision':''} ${TILES.length>20?'large-map':''} ${mapMotion?`map-shuffling-${mapMotion.phase}`:''}`} data-map-size={TILES.length} style={{'--columns':dimensions.columns,'--rows':dimensions.rows,'--map-min-width':`${dimensions.columns*64}px`,...viewport.boardStyle}}>{TILES.map((t,i)=>{const prop=game.properties[i];return <button key={i} className={`tile ${t.type} ${selected===i?'selected':''} ${prop?.owner==='bank'?'bank-held':''} ${shownPosition(game.current)===i?'occupied':''} ${motion?.path.includes(i)?'on-route':''} ${motion?.to===i?'destination':''} ${motion?.phase==='land'&&motion.to===i?'arrival':''}`} style={{...position(i),'--shuffle-x':`${mapMotion?.offsets[i]?.x||0}px`,'--shuffle-y':`${mapMotion?.offsets[i]?.y||0}px`,'--shuffle-delay':`${i%7*25}ms`,'--industry-color':t.color||'#b8c7a1','--region-color':GROUPS[t.group]?.color||'#b8c7a1','--owner-color':ownerColor(game,prop),'--actor-color':current.color}} onClick={()=>{setSelected(i);setModal(t.type==='city-event'?'city-events':'tile');}} data-tile={i} aria-label={`${t.name}${prop?`，${ownerName(game,prop)}拥有`:''}`}>
 {t.type==='industry'?<><div className="industry-strip"/><img className="industry-sprite" src={t.asset} alt=""/><b>{t.shortName||t.name}</b><span className="tile-price">{prop?prop.owner==='bank'?'银行代持':ownerName(game,prop):money(t.price)}</span></>:t.type==='city'?<><div className="region-strip"/><img className="city-sprite" src={t.asset} alt=""/><b>{t.name}</b><span className="tile-price">{prop?prop.owner==='bank'?'银行代持':`${ownerName(game,prop)} · ${prop.level+1} 级`:money(t.price)}</span></>:<><img className="station-sprite" src={`/assets/stations/${t.type}.svg`} alt=""/><b>{t.name}</b><span className="special-caption">{({start:'经过 +1,000',chance:'奇遇抽卡','city-event':'本局城市卡'})[t.type]}</span></>}
 {prop&&<span className="owner-indicator"/>}{motion?.path.includes(i)&&<span className="route-step">{motion.path.indexOf(i)+1}</span>}

 </button>})}
 <div className="token-layer">{game.players.map((p,id)=>{if(p.bankrupt)return null;const at=shownPosition(id),pos=position(at),walking=motion?.player===id&&motion.phase==='walk',active=game.current===id;const others=game.players.map((q,j)=>!q.bankrupt&&shownPosition(j)===at?j:-1).filter(j=>j>=0);const visible=others.length>4?[...others.filter(j=>j===game.current),...others.filter(j=>j!==game.current)].slice(0,3):others;if(!visible.includes(id))return null;const offset=(visible.indexOf(id)-(visible.length-1)/2)*13;return <button key={id} aria-label={`查看${p.name}的资产`} onClick={()=>openToken(id)} className={`board-token ${active?'active-token':''} ${walking?'walking':''} ${motion?.player===id&&motion.phase==='teleport'?'teleporting':''} ${motion?.phase==='land'&&motion.player===id?'landed':''}`} data-token={id} data-position={at} style={{left:`${(pos.gridColumn-.5)/dimensions.columns*100}%`,top:`${(pos.gridRow-.5)/dimensions.rows*100}%`,'--token-color':p.color,'--slot':`${offset}px`}}><span className="token-shadow"/><div className="token-body"><PixelPlayer player={game.players[id]} id={id} frame={walking?motion.step%2:null}/></div><span className="token-name">{p.name}{active&&<i/>}</span>{others.length>4&&id===visible.at(-1)&&<span className="token-count">{others.length} 人</span>}</button>})}</div>
 <BoardHub mapMotion={mapMotion} game={game} motion={motion} finance={finance} animating={animating} onWallet={openWallet} onCard={setModal} style={{gridColumn:`2 / ${dimensions.columns}`,gridRow:`2 / ${dimensions.rows}`}}/>
 {viewport.desktop&&decision&&<div className="board-decision" style={{gridColumn:`2 / ${dimensions.columns}`,gridRow:`2 / ${dimensions.rows}`}}>{decision}</div>}
 </div></div></div>
 <div className="board-legend"><div>{Object.entries(GROUPS).map(([key,g])=><span key={key}><i style={{background:g.color}}/>{g.name}</span>)}</div><span><HelpCircle size={13}/>点击地块查看详情</span></div>
 {decision?(viewport.desktop?<div className="turn-bar decision-status"><button className="turn-avatar" aria-label={`查看${current.name}的资产`} onClick={()=>openWallet(game.current)}><PixelPlayer player={current} id={game.current}/></button><div className="turn-message"><h3>{current.name} · {neutralText(game.notice)}</h3></div><Die value={game.dice}/></div>:decision):<div className={`turn-bar ${busy?'ai-turn':''}`}><button className="turn-avatar" aria-label={`查看${current.name}的资产`} onClick={()=>openWallet(game.current)}><PixelPlayer player={game.players[game.current]} id={game.current}/></button><div className="turn-message"><h3>{game.phase==='finished'?'对局已结束':animating?(mapMotion?'城市正在重排':finance?finance.label:motion?.phase==='teleport'?`${current.name}前往${TILES[motion.to].name}`:motion?.phase==='walk'?`${current.name}正在前往${TILES[motion.to].name} · 第 ${motion.step}/${motion.total} 步`:motion?.phase==='land'?`抵达${TILES[motion.to].name}`:'骰子转动中…'):busy?`${current.name}行动中`:game.phase==='roll'?'你的回合':game.phase==='buy'?`${TILES[human.pos].name} · 可购买`:game.phase==='upgrade'?`${TILES[human.pos].name} · 可升级`:neutralText(game.notice)}</h3>{!animating&&game.current===0&&game.phase==='roll'&&human.controlled&&<p>遥控骰子：{human.controlled} 步</p>}{!animating&&game.current===0&&game.phase==='buy'&&(TILES[human.pos].type==='industry'?<p className="industry-purchase-note">公共事业 · 不可升级 · 当前服务费预览 {money(getIndustryQuote(game,human.pos,0,0).amount)}</p>:<p>基础租金 {money(Math.round(TILES[human.pos].price*.16))} / 次</p>)}{!animating&&game.current===0&&game.phase==='upgrade'&&<p>升级至 {game.properties[human.pos].level+2} 级</p>}</div><div className={`dice-preview ${rolling?'rolling':''}`}><Die value={motion?displayDice:game.dice}/></div><div className="turn-actions">{game.phase==='finished'?<button className="primary" onClick={()=>setModal('result')}><Trophy size={19}/>查看结果</button>:animating?<button className="primary" disabled>{mapMotion?'城市重排中…':finance?'金币结算中…':motion?.phase==='teleport'?'正在传送…':motion?.phase==='walk'?'正在移动…':motion?.phase==='land'?'已到站':'掷骰中…'}</button>:game.current!==0?<button className="primary" disabled>AI 行动中<span className="thinking">···</span></button>:game.phase==='roll'?<button className="primary roll-button" disabled={rolling} onClick={roll}><Dices size={20}/>{rolling?'掷骰中…':'掷骰子'}</button>:<>{game.phase==='buy'&&<button className="primary" onClick={()=>dispatch({type:'BUY'})}>购买 {money(TILES[human.pos].price)}</button>}{game.phase==='upgrade'&&<button className="primary" onClick={()=>dispatch({type:'UPGRADE'})}>升级 {money(upgradeCost(game,human.pos))}</button>}<button className={game.phase==='end'?'primary':'text-button'} onClick={finishTurn}>{game.phase==='end'?(game.testRun?'选择下一张卡':'结束回合'):game.phase==='buy'?'不购买':'不升级'}<ArrowRight size={16}/></button></>}</div></div>}

 </section>:<CityLibrary tiles={TILES} onSelect={city=>{setCatalogCity(city);setModal('catalog');}}/>}

 </div></div><footer><span>monopoly</span><span>{saved?<><Check size={12}/>{game.testRun?'测试进度已保存 · 原对局保留':'进度已自动保存'}</>:<>当前浏览器无法保存进度</>}<i/>浏览器原型 v0.1</span></footer>
 </main>
 <MoneyEffects event={finance} players={game.players}/>
  <FxLayer commit={commit} game={game} play={playSound} onFinale={()=>{if(!game.testRun)setModal('result');}}/>
  <DiceRoll rolling={rolling} value={displayDice} color={current.color}/>
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section role="dialog" aria-modal="true" aria-label="游戏详情" className={`modal ${modal==='event-lab'?'event-lab-modal':modal==='city-events'?'city-events-modal':modal==='tile'&&TILES[selected]?.type==='industry'?'industry-modal':modal==='rules'?'rules-modal':['appearance','add-player','map'].includes(modal)?'appearance-modal':''}`} onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="关闭" onClick={()=>setModal(null)}><X size={20}/></button>
 {modal==='event-lab'&&<EventLabPicker game={game} onStart={startEventTest}/>}
 {modal==='city-events'&&<CityEvents game={game}/>}
 {modal==='map'&&<MapEditor map={game.map} rounds={Number.isFinite(roundLimit(game))?roundLimit(game):null} currentRound={game.round} onCancel={()=>setModal(null)} onSaveRounds={game.phase==='finished'?undefined:limit=>{setRoundLimit(limit);setModal(null);}} onApply={(map,rounds)=>{reset(map,rounds);setSelected(null);setModal(null);setTab('game');}}/>}
 {modal==='add-player'&&newCharacter&&<AppearanceEditor key="new-character" creating player={newCharacter} id={game.players.length} onSave={(appearance,name)=>{const error=addCharacter({name,appearance});if(error)return error;setModal(null);}} onCancel={()=>setModal(null)}/>}
 {modal==='appearance'&&<AppearanceEditor key={wallet} player={game.players[wallet]} id={wallet} onSave={(appearance,name)=>{const error=renameCharacter(wallet,name);if(error)return error;updateAppearance(wallet,appearance);setModal('wallet');}} onCancel={()=>setModal(null)}/>}
 {modal==='catalog'&&catalogCity&&<CatalogCityDetails tiles={TILES} city={catalogCity} onBoardDetails={index=>{setSelected(index);setModal('tile');}}/>}
 {modal==='participants'&&<><h2>选择玩家</h2><div className="participant-picker">{participants.map(id=><button key={id} onClick={()=>openWallet(id)} aria-label={`查看${game.players[id].name}的资产`}><PixelPlayer player={game.players[id]} id={id}/><b>{game.players[id].name}</b></button>)}</div></>}
 {modal==='wallet'&&<><div className="wallet-portrait"><PixelPlayer player={game.players[wallet]} id={wallet}/></div><h2>{game.players[wallet].name}</h2><button className="wallet-edit" onClick={()=>setModal('appearance')}>编辑昵称与外观</button><div className="detail-stats"><div><small>可用现金</small><b>{money(game.players[wallet].cash)}</b></div><div><small>产权净值</small><b>{money(propertyEquity(game,wallet))}</b></div><div><small>总资产</small><b>{money(worth(game,wallet))}</b></div></div><PropertyPortfolio game={game} id={wallet} animating={animating} dispatch={dispatch} onIndustry={index=>{setSelected(index);setModal('tile');}}/>{game.debt&&game.current===wallet&&<p className="detail-note">待付款 {money(game.debt.amount)}</p>}<p className="detail-note">总资产 = 现金 + 产权净值 − 待付款。抵押产权净值已扣除抵押款。</p><button className="primary wide" onClick={()=>setModal(null)}>返回棋盘 <ArrowRight size={16}/></button></>}
 {modal==='rules'&&<><div className="modal-emblem"><Compass size={32}/></div><h2>游戏规则</h2><p>1 位玩家与 {game.players.length-1} 位 AI 对局。{Number.isFinite(roundLimit(game))?`${roundLimit(game)} 轮后，总资产最高者获胜；`:'不限轮数；可在“重新开始”中立即结算，'}如果只剩一人未破产，提前结算。轮数在“地图设置”中调整。</p><div className="rules-grid">{[['01','掷骰与购城','每回合掷出 1～6 点，停留在无主城市时可以购买。经过起点获得 ¥1,000，小满额外获得 ¥200。'],['02','经营与收租','对手到访你的城市时支付租金。回到自己的城市可以升级，最高 4 级。总资产 = 现金 + 产权净值 − 待付款。'],['03','区域与季节','集齐当前地图同色组的全部城市，租金 ×1.5。每 4 轮更换旅行季，对应区域租金 ×1.3，可叠加。'],['04','卡牌与奇遇','奇遇格抽通用事件，城市事件格只抽本局城市卡。道具由事件发放。事件可收付资金、重排城市、移动、获得道具、升级或赎回地产；需要选择时按卡面操作。移动不领起点奖励，到站照常结算。道具在掷骰前使用。'],['05','收购产权','城市付租或产业付服务费前可提出收购。城市报价为原价加实际升级支出，产业按原价；业主同意则转让产权并免本次费用。'],['06','银行抵押','城市抵押款为原价的 50% 加实际升级支出，产业为原价的 50%。银行代持期间不收费、不可购买，可原额赎回。无可抵押资产且仍欠款时破产，全部产权回流，城市等级归零。'],['07','公共事业','铁路、航空、航运、太空冒险、水电可购买及收购，不可升级。服务费按骰点、轮次、来客城市与同业主产业联动计算，点击地块查看公式。抵押暂停收费和联动，城市护盾及租金加成不适用。']].map(([n,h,p])=><div key={n}><small>{n}</small><h3>{h}</h3><p>{p}</p></div>)}</div><button className="primary wide" onClick={()=>setModal(null)}>关闭 <ArrowRight size={17}/></button></>}
 {modal==='restart'&&<><div className="modal-emblem"><RotateCcw size={30}/></div><h2>重新开始对局？</h2><p>当前进度将被清除，角色名单与外观保留。每位玩家初始现金为 ¥12,000。</p><button className="primary wide" onClick={()=>{reset();setModal(null);setTab('game');}}>确认重开</button>{['roll','end'].includes(game.phase)&&game.current===0&&!animating&&!game.testRun&&<button className="text-button wide" onClick={()=>{setModal(null);dispatch({type:'SETTLE'});}}>立即结算（按当前总资产排名）</button>}<button className="text-button wide" onClick={()=>setModal(null)}>取消</button></>}
 {CARDS[modal]&&<><div className={`modal-emblem ${modal}`}>{React.createElement(CARDICON[modal],{size:32})}</div><h2>{CARDS[modal].name}</h2><p>{CARDS[modal].detail}</p>{modal==='dice'?<><div className="dice-options">{[1,2,3,4,5,6].map(v=><button key={v} aria-label={`选择 ${v} 点`} onClick={()=>useCard('dice',v)}><Die value={v}/><span>{TILES[(human.pos+v)%TILES.length].name}</span></button>)}</div><p className="muted">选择步数后，点击“掷骰子”移动。</p></>:<button className="primary wide" onClick={()=>useCard(modal)}>使用 <Sparkles size={16}/></button>}</>}
 {modal==='tile'&&selected!==null&&(()=>{const t=TILES[selected],prop=game.properties[selected];if(t.type==='industry')return <IndustryDetails key={t.industryId} game={game} index={selected} onClose={()=>setModal(null)}/>;return <><div className="detail-art" style={{background:GROUPS[t.group]?.color+'25'}}>{t.type==='city'?<img src={t.asset} alt={`${t.name}像素地标`}/>:special(t,60)}</div><div className="eyebrow">{GROUPS[t.group]?.name||'特殊格'}</div><h2>{t.name}</h2>{t.type!=='city'&&<p>{t.desc}</p>}{t.type==='city'&&<><div className="detail-stats"><div><small>城市价值</small><b>{money(t.price)}</b></div><div><small>{prop?'当前租金':'基础租金'}</small><b>{money(prop?rent(game,selected):Math.round(t.price*.16))}</b></div><div><small>持有者</small><b>{prop?ownerName(game,prop):'无'}</b></div></div><p className="detail-note">{prop?.owner==='bank'?`银行代持 · 原持有人 ${game.players[prop.mortgagor].name} · 免租，不可购买。 `:''}{prop?`当前 ${prop.level+1} 级 / 最高 4 级`:'停留在此格时可购买'} · 集齐当前地图同色组全部城市，租金 +50%</p></>}<button className="primary wide" onClick={()=>setModal(null)}>返回棋盘 <ArrowRight size={16}/></button></>;})()}
 {modal==='result'&&<><div className="modal-emblem"><Trophy size={32}/></div><h2>{game.players[game.winner]?.name}获胜</h2><p>按总资产排名。</p><Podium game={game}/><div className="ranking animated">{game.players.map((p,id)=>({...p,id,total:worth(game,id)})).sort((a,b)=>b.total-a.total).map((p,i)=><div key={p.id}><b>{i+1}</b><PixelPlayer player={game.players[p.id]} id={p.id}/><span>{p.name}</span><strong>{money(p.total)}</strong></div>)}</div><button className="primary wide" onClick={()=>setModal('restart')}>重新开始 <ArrowRight size={16}/></button></>}
 </section></div>}
 </div>;
}
function DiceLogo(){return <svg viewBox="0 0 30 30" fill="none"><path d="M5 2H25V5H28V25H25V28H5V25H2V5H5Z" fill="#37735a"/><path d="M7 7H12V12H7ZM18 7H23V12H18ZM12.5 12.5H17.5V17.5H12.5ZM7 18H12V23H7ZM18 18H23V23H18Z" fill="#f8f2df"/></svg>}
createRoot(document.getElementById('root')).render(<App/>);
